"""
Every derived brand asset, from one source file.

    python scripts/build-brand-assets.py

The source is packages/ui/brand/nexg-mark.png. Everything this
writes is generated and committed — favicons for both apps, the
Apple touch icons, and the base64 centre mark the QR encoder stamps
into each card. Regenerate rather than editing any of them by hand,
or they drift and the card stops matching the tab.

Two decisions worth knowing about:

  * The mark is padded to a square with transparency rather than
    stretched. The source is 511x461 and a favicon is square; a
    stretched cloche is noticeably wrong at 32px.
  * The QR centre mark is deliberately small. Error-correction level
    H tolerates roughly 30% loss, the plate covers about 5% of the
    area, and apps/web/scripts/verify-qr.mjs proves a code still
    decodes with that square blanked out. Growing it past the tested
    budget means re-running that check, not guessing.
"""

import base64
import io
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "packages/ui/brand/nexg-mark.png"

try:
    from PIL import Image
except ImportError:  # pragma: no cover
    raise SystemExit("Pillow is needed: pip install Pillow")


def squared(im, pad_ratio=0.06):
    """Trim to the ink, then centre it on a transparent square.

    Favicons are square and the mark is not. Padding keeps the
    proportions a designer drew; stretching to fit does not.
    """
    im = im.convert("RGBA")
    box = im.getbbox()
    if box:
        im = im.crop(box)

    side = int(max(im.size) * (1 + pad_ratio * 2))
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(im, ((side - im.width) // 2, (side - im.height) // 2), im)
    return canvas


def main():
    if not SOURCE.exists():
        raise SystemExit(f"No source mark at {SOURCE}")

    mark = squared(Image.open(SOURCE))
    print(f"source {SOURCE.name} -> square {mark.size[0]}px")

    for app in ("web", "admin"):
        app_dir = ROOT / "apps" / app / "app"
        if not app_dir.exists():
            print(f"  skipping {app}: no app directory")
            continue

        mark.resize((512, 512), Image.LANCZOS).save(app_dir / "icon.png", optimize=True)

        # Apple wants an opaque icon; a transparent one renders black
        # on the home screen of every iPhone it lands on.
        apple = Image.new("RGBA", mark.size, (255, 255, 255, 255))
        apple.alpha_composite(mark)
        apple.convert("RGB").resize((180, 180), Image.LANCZOS).save(
            app_dir / "apple-icon.png", optimize=True
        )

        # A .ico carries several sizes; the browser picks. 16 and 32
        # are the tab, 48 is the bookmarks bar, 64 the task switcher.
        mark.save(
            app_dir / "favicon.ico",
            sizes=[(16, 16), (32, 32), (48, 48), (64, 64)],
        )
        print(f"  {app}: icon.png, apple-icon.png, favicon.ico")

    # ── the mark the QR encoder stamps into every card ───────────
    #
    # 128px is plenty: it lands in a ~110px square on a 512px code
    # and is only ever scaled down from there. Written as base64 in
    # a TypeScript file rather than read from disk at request time,
    # so the encoder has no filesystem dependency and works the same
    # in every runtime.
    centre = mark.resize((128, 128), Image.LANCZOS)
    buf = io.BytesIO()
    centre.save(buf, format="PNG", optimize=True)
    encoded = base64.b64encode(buf.getvalue()).decode("ascii")

    out = ROOT / "apps/web/lib/qr-mark.ts"
    out.write_text(
        "/*\n"
        " * The NexG mark, as it appears in the middle of every card.\n"
        " *\n"
        " * Generated by scripts/build-brand-assets.py from\n"
        " * packages/ui/brand/nexg-mark.png. Do not edit by hand — run\n"
        " * the script, or the card stops matching the favicon.\n"
        " *\n"
        " * Inlined rather than fetched so the encoder has no network\n"
        " * or filesystem dependency: a card that renders without its\n"
        " * logo because an image 404'd is a card somebody prints.\n"
        " */\n"
        f"export const QR_MARK_PNG =\n  'data:image/png;base64,{encoded}';\n",
        encoding="utf-8",
    )
    print(f"  qr-mark.ts: {len(encoded) // 1024} KB base64")


if __name__ == "__main__":
    main()
